### ISSUE TITLE
Recommend the Awesome PHP

### ISSUE THREAD

**Issue by ghost** [funfunhey/myweibo#1]
ThinkPHP is Not a Good Choice for Building Testable and Maintainable Web Appliction.
ThinkPHP Makes the Code Unreadable and Waste Many of Your Time.
Here's A Good List of Awesome Frameworks:
[https://github.com/ziadoz/awesome-php#frameworks](https://github.com/ziadoz/awesome-php#frameworks)

Enjoy it :rocket:

**Comment by funfunhey** [comment]
this is my first time to build a web appliction ，i  learned  php 5months ago and i need a framework to complete this project ,so i choose a simple framework.好了，说人话。。。中式英语不说了，thinkphp的确挺慢的，感受到了
